import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { listCashAccounts } from '../../api/cashAccounts'
import { addSalaryAdjustment, confirmSalaryPeriod, deleteSalaryAdjustment, getSalaryPeriod, paySalaryPeriod, recalculateSalaryPeriod } from '../../api/salaryPeriods'
import type { CashAccountOption } from '../../types/cashAccount'
import type { SalaryPeriod, SalarySettlement } from '../../types/salary'
import { generateIdempotencyKey } from '../../utils/idempotency'
import { SalaryStatusBadge } from './shared'
import { apiError, formatCurrency, formatPercent } from './salaryUtils'

const itemLabels:Record<string,string>={base_salary:'底薪',fixed_allowance:'固定津貼',purchase_bonus:'收車獎金',sales_bonus:'賣車獎金',labor_insurance_deduction:'勞保扣款',health_insurance_deduction:'健保扣款',manual_addition:'其他加給',manual_deduction:'其他扣款'}
function correctionPath(action:string,vehicleId:number,context:Record<string,unknown>){if(action==='commission_attribution')return '/vehicles/commission-attribution';if(action==='salary_period'){const ids=context.salary_period_ids as number[]|undefined;return ids?.[0]?`/salary/periods/${ids[0]}`:`/vehicles/${vehicleId}`}return `/vehicles/${vehicleId}`}

export function SalaryPeriodDetail(){
  const id=Number(useParams().id); const [period,setPeriod]=useState<SalaryPeriod|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [expanded,setExpanded]=useState<number|null>(null)
  const [adjust,setAdjust]=useState<{user_id:number;type:'manual_addition'|'manual_deduction';amount:string;description:string}|null>(null); const [accounts,setAccounts]=useState<CashAccountOption[]>([]); const [payForm,setPayForm]=useState({cash_account_id:'',payment_date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}),idempotency_key:generateIdempotencyKey()})
  const load=()=>{setError(null);getSalaryPeriod(id).then(setPeriod).catch(e=>setError(apiError(e,'薪資月份載入失敗')))}; useEffect(load,[id]); useEffect(()=>{listCashAccounts().then(a=>setAccounts(a.filter(x=>x.is_active))).catch(()=>{})},[])
  async function action(run:()=>Promise<unknown>){setBusy(true);setError(null);try{await run();load()}catch(e){setError(apiError(e,'薪資操作失敗'))}finally{setBusy(false)}}
  if(!period)return <p className={error?'text-error':'text-fg-muted'}>{error??'載入中...'}</p>
  const tiers=[...period.commission_plan.tiers].sort((a,b)=>a.min_sales_count-b.min_sales_count)
  function tierText(s:SalarySettlement){const next=tiers.find(t=>t.min_sales_count>s.eligible_sales_count);return next?`再 ${next.min_sales_count-s.eligible_sales_count} 台升至 ${formatPercent(next.sales_bonus_bps)}`:'已達最高級距'}
  async function add(){if(!adjust)return;await action(async()=>{await addSalaryAdjustment(id,{...adjust,amount:Number(adjust.amount)});setAdjust(null)})}
  return <div className="flex flex-col gap-6">
    <div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-3"><h1 className="text-xl font-semibold text-fg">{period.period_month} 薪資</h1><SalaryStatusBadge status={period.status}/></div><p className="mt-1 text-sm text-fg-muted">適用方案：{period.commission_plan.name}</p></div><Link to="/salary" className="text-sm text-primary">返回薪資月份</Link></div>
    {error&&<p className="rounded-lg bg-error/10 p-3 text-sm text-error">{error}</p>}
    <section className="grid gap-4 sm:grid-cols-3"><Summary label="全公司實發合計" value={formatCurrency(period.totals.net_pay)}/><Summary label="公司營運保留" value={formatCurrency(period.totals.company_reserve_total)}/><Summary label="公司剩餘分配額" value={formatCurrency(period.totals.company_remaining_total)}/></section>
    {period.status==='draft'&&<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>action(()=>recalculateSalaryPeriod(id))} className="rounded-lg border border-border-strong px-4 py-2 text-sm">重算草稿</button><button disabled={busy||period.has_blocking_issues} onClick={()=>{if(window.confirm('確認後薪資快照與車輛歸屬將鎖定，確定要確認結算？'))action(()=>confirmSalaryPeriod(id))}} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-fg disabled:opacity-50">確認結算</button></div>}
    {period.status==='confirmed'&&<section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-semibold">發薪</h2><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-sm">資金帳戶 <span className="text-error">*</span><select value={payForm.cash_account_id} onChange={e=>setPayForm({...payForm,cash_account_id:e.target.value,idempotency_key:generateIdempotencyKey()})} className="mt-1 block rounded-lg border border-border-strong bg-surface px-3 py-2"><option value="">請選擇</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="text-sm">發薪日期 <span className="text-error">*</span><input type="date" value={payForm.payment_date} onChange={e=>setPayForm({...payForm,payment_date:e.target.value,idempotency_key:generateIdempotencyKey()})} className="mt-1 block rounded-lg border border-border-strong bg-surface px-3 py-2"/></label><button disabled={busy||!payForm.cash_account_id} onClick={()=>{if(window.confirm(`確定由所選帳戶發放 ${formatCurrency(period.totals.net_pay)}？`))action(()=>paySalaryPeriod(id,{cash_account_id:Number(payForm.cash_account_id),payment_date:payForm.payment_date,idempotency_key:payForm.idempotency_key}))}} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-fg disabled:opacity-50">確認發薪</button></div></section>}
    {period.status==='paid'&&<p className="rounded-lg bg-success/10 p-3 text-sm text-success">已於 {period.payment_date} 由 {period.cash_account?.name??'指定帳戶'} 發薪，本月份唯讀。</p>}
    {period.status==='draft'&&period.anomalies&&period.anomalies.length>0&&<section className="rounded-2xl border border-error/30 bg-surface p-5"><h2 className="font-semibold text-error">阻擋異常（{period.anomalies.length}）</h2><div className="mt-3 grid gap-2">{period.anomalies.map((a,i)=><div key={`${a.vehicle_id}-${a.code}-${i}`} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-error/5 p-3 text-sm"><span><b>{a.stock_no}</b>：{a.message}</span><Link to={correctionPath(a.correction.action,a.vehicle_id,a.context)} className="font-medium text-primary">{a.correction.label}</Link></div>)}</div></section>}
    <div className="grid gap-4">{period.settlements.map(s=><section key={s.id} className="rounded-2xl border border-border bg-surface p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-fg">{s.user.name}</h2><p className="text-xs text-fg-muted">當月成交 {s.eligible_sales_count} 台・適用 {formatPercent(s.sales_bonus_bps)}・{tierText(s)}</p></div><div className="text-right"><p className="text-xs text-fg-muted">實發薪資</p><p className="text-xl font-bold tabular-nums">{formatCurrency(s.net_pay)}</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-3 lg:grid-cols-5"><Metric label="底薪" value={s.base_salary}/><Metric label="固定津貼" value={s.fixed_allowance}/><Metric label="收車獎金" value={s.purchase_bonus_total}/><Metric label="賣車獎金" value={s.sales_bonus_total}/><Metric label="其他加給" value={s.manual_addition_total}/><Metric label="勞保扣款" value={s.labor_insurance_deduction}/><Metric label="健保扣款" value={s.health_insurance_deduction}/><Metric label="其他扣款" value={s.manual_deduction_total}/></div><div className="mt-4 flex gap-2"><button onClick={()=>setExpanded(expanded===s.id?null:s.id)} className="text-sm font-medium text-primary">{expanded===s.id?'收合明細':'展開薪資與車輛獎金明細'}</button>{period.status==='draft'&&<button onClick={()=>setAdjust({user_id:s.user_id,type:'manual_addition',amount:'',description:''})} className="text-sm text-fg-muted">新增加扣項</button>}</div>{expanded===s.id&&<div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><tbody className="divide-y divide-border">{s.items.map(item=><tr key={item.id}><td className="py-2">{itemLabels[item.type]??item.type}</td><td className="py-2">{item.vehicle?<Link className="text-primary" to={`/vehicles/${item.vehicle.id}`}>{item.vehicle.stock_no} {item.vehicle.brand} {item.vehicle.model}</Link>:item.description}</td><td className="py-2 text-right tabular-nums">{formatCurrency(item.amount)}</td><td className="py-2 text-right">{period.status==='draft'&&item.type.startsWith('manual_')&&<button onClick={()=>action(()=>deleteSalaryAdjustment(id,item.id))} className="text-error">刪除</button>}</td></tr>)}</tbody></table></div>}</section>)}</div>
    {adjust&&<div className="fixed inset-0 z-20 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-surface p-6"><h2 className="font-semibold">新增手動加扣項</h2><div className="mt-4 grid gap-3"><label className="text-sm">類型 <span className="text-error">*</span><select value={adjust.type} onChange={e=>setAdjust({...adjust,type:e.target.value as typeof adjust.type})} className="mt-1 w-full rounded-lg border border-border-strong bg-surface px-3 py-2"><option value="manual_addition">其他加給</option><option value="manual_deduction">其他扣款</option></select></label><label className="text-sm">金額 <span className="text-error">*</span><input type="number" min="1" value={adjust.amount} onChange={e=>setAdjust({...adjust,amount:e.target.value})} className="mt-1 w-full rounded-lg border border-border-strong bg-surface px-3 py-2"/></label><label className="text-sm">說明 <span className="text-error">*</span><input maxLength={255} value={adjust.description} onChange={e=>setAdjust({...adjust,description:e.target.value})} className="mt-1 w-full rounded-lg border border-border-strong bg-surface px-3 py-2"/></label></div><div className="mt-4 flex gap-2"><button disabled={busy||!adjust.amount||!adjust.description} onClick={add} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-fg disabled:opacity-50">新增</button><button onClick={()=>setAdjust(null)} className="rounded-lg border border-border-strong px-4 py-2 text-sm">取消</button></div></div></div>}
  </div>
}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-border bg-surface p-5"><p className="text-sm text-fg-muted">{label}</p><p className="mt-2 text-2xl font-bold tabular-nums">{value}</p></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-lg bg-surface-2 p-3"><p className="text-xs text-fg-muted">{label}</p><p className="font-semibold tabular-nums">{formatCurrency(value)}</p></div>}
