import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { listSalaryProfiles, updateSalaryProfile } from '../../api/salaryProfiles'
import { listUsers } from '../../api/users'
import type { SalaryProfile, SalaryProfilePayload } from '../../types/salary'
import type { User } from '../../types/user'
import { apiError, apiValidationErrors } from './salaryUtils'

export function SalaryProfiles() {
  const [profiles, setProfiles] = useState<SalaryProfile[]>([]); const [users,setUsers]=useState<User[]>([]); const [editing, setEditing] = useState<number | null>(null)
  const [form, setForm] = useState<SalaryProfilePayload | null>(null); const [error, setError] = useState<string | null>(null); const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({}); const [saving, setSaving] = useState(false)
  const load = () => Promise.all([listSalaryProfiles(),listUsers()]).then(([loadedProfiles,loadedUsers])=>{setProfiles(loadedProfiles);setUsers(loadedUsers)}).catch((e) => setError(apiError(e, '薪資設定載入失敗')))
  useEffect(() => { load() }, [])
  const start = (p: SalaryProfile) => { setEditing(p.user_id); setForm({ base_salary:p.base_salary,fixed_allowance:p.fixed_allowance,labor_insurance_deduction:p.labor_insurance_deduction,health_insurance_deduction:p.health_insurance_deduction,commission_enabled:p.commission_enabled,is_active:p.is_active }) }
  async function save() { if (!editing || !form) return; setSaving(true); setError(null); setFieldErrors({}); try { await updateSalaryProfile(editing, form); setEditing(null); load() } catch(e) { setFieldErrors(apiValidationErrors(e)); setError(apiError(e,'儲存薪資設定失敗')) } finally { setSaving(false) } }
  const rows:SalaryProfile[]=users.map(user=>profiles.find(profile=>profile.user_id===user.id)??{id:-user.id,user_id:user.id,user:{id:user.id,name:user.name,email:user.email,role:user.role,is_active:user.is_active},base_salary:0,fixed_allowance:0,labor_insurance_deduction:0,health_insurance_deduction:0,commission_enabled:false,is_active:false})
  return <div className="flex flex-col gap-6"><div className="flex justify-between"><div><h1 className="text-xl font-semibold text-fg">員工薪資設定</h1><p className="mt-1 text-sm text-fg-muted">變更只影響未確認月份，不會回改歷史薪資快照。</p></div><Link to="/salary" className="text-sm text-primary">返回薪資月份</Link></div>{error && <p className="text-sm text-error">{error}</p>}
  <div className="grid gap-4">{rows.map((p) => <section key={p.user_id} className="rounded-2xl border border-border bg-surface p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="font-semibold text-fg">{p.user.name}</h2><p className="text-xs text-fg-muted">{p.user.email}{p.id<0?'・尚未設定薪資':''}</p></div>{editing !== p.user_id && <button onClick={() => start(p)} className="rounded-lg border border-border-strong px-3 py-1.5 text-sm">{p.id<0?'建立設定':'編輯'}</button>}</div>
  {editing === p.user_id && form ? <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([['base_salary','底薪'],['fixed_allowance','固定津貼'],['labor_insurance_deduction','勞保扣款'],['health_insurance_deduction','健保扣款']] as const).map(([key,label]) => <label key={key} className="text-sm text-fg-muted">{label} <span className="text-error">*</span><input type="number" min="0" required value={form[key]} onChange={(e) => setForm({...form,[key]:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-border-strong bg-surface px-3 py-2 text-fg" />{fieldErrors[key]&&<span className="mt-1 block text-xs text-error">{fieldErrors[key]}</span>}</label>)}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.commission_enabled} onChange={(e)=>setForm({...form,commission_enabled:e.target.checked})}/>啟用獎金</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={(e)=>setForm({...form,is_active:e.target.checked})}/>納入薪資結算</label><div className="sm:col-span-2 lg:col-span-4 flex gap-2"><button disabled={saving} onClick={save} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-fg">{saving?'儲存中...':'儲存'}</button><button onClick={()=>setEditing(null)} className="rounded-lg border border-border-strong px-4 py-2 text-sm">取消</button></div></div> : <div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><span>底薪<br/><b>{p.base_salary.toLocaleString()}</b></span><span>固定津貼<br/><b>{p.fixed_allowance.toLocaleString()}</b></span><span>勞保<br/><b>{p.labor_insurance_deduction.toLocaleString()}</b></span><span>健保<br/><b>{p.health_insurance_deduction.toLocaleString()}</b></span><span>獎金<br/><b>{p.commission_enabled?'啟用':'停用'}</b></span><span>結算<br/><b>{p.is_active?'納入':'停用'}</b></span></div>}</section>)}</div></div>
}
